#Requires -Version 5.1
<#
.SYNOPSIS
  Build patet-back-nestjs and/or patet-website on Windows, upload to Ubuntu, finalize on server.

.DESCRIPTION
  Primary deploy path: local yarn build -> rsync/scp release -> finalize-release.sh on VPS.
  Fallback: push git to Bitbucket, SSH and run ./deploy.sh on the server (see README).

.PARAMETER Target
  backend | frontend | all

.PARAMETER SkipBuild
  Upload only (artifacts must already exist locally).

.PARAMETER Migrate
  Run backend migrations during finalize (default: skip migrations).

.PARAMETER SkipUpload
  Build only; do not upload or finalize.

.PARAMETER ReleaseId
  Override release folder name (default: Asia/Yerevan-style timestamp yyyy-MM-dd_HHmmss).

.PARAMETER SyncDeploymentScripts
  Rsync patet-deployment scripts to PATET_DEPLOYMENT_ROOT on the server before finalize.

.NOTES
  Run with no parameters to open an interactive menu:
  1 backend only, 2 frontend only, 3 back+front, 4 back+front+migrate, 5 more options.
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('backend', 'frontend', 'all')]
    [string] $Target = 'all',

    [switch] $SkipBuild,
    [switch] $Migrate,
    [switch] $SkipUpload,
    [switch] $SyncDeploymentScripts,

    [string] $ReleaseId = '',

    [ValidateSet('default', 'patet-am', 'commercial')]
    [string] $Profile = 'default'
)

$ErrorActionPreference = 'Stop'

$DeploymentDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BackAndFrontRoot = Split-Path -Parent $DeploymentDir
$script:FrontendBuildEnv = @{}
$script:DeployProfileLabel = ''
$script:DeployProfileName = ''

function Write-Step([string] $Message) {
    Write-Host ""
    Write-Host "==== $Message ====" -ForegroundColor Cyan
}

function Import-DeployLocalEnv {
    param([string] $Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        return $false
    }
    Get-Content -LiteralPath $Path | ForEach-Object {
        $line = $_.Trim()
        if ($line -eq '' -or $line.StartsWith('#')) { return }
        $eq = $line.IndexOf('=')
        if ($eq -lt 1) { return }
        $name = $line.Substring(0, $eq).Trim()
        $value = $line.Substring($eq + 1).Trim()
        if ($value.StartsWith('"') -and $value.EndsWith('"')) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        if ($name.StartsWith('FRONTEND_BUILD_')) {
            $envKey = $name.Substring('FRONTEND_BUILD_'.Length)
            $script:FrontendBuildEnv[$envKey] = $value
            return
        }
        if ($name -eq 'PATET_PROFILE_LABEL') {
            $script:DeployProfileLabel = $value
            return
        }
        Set-Item -Path "Env:$name" -Value $value
    }
    return $true
}

function Resolve-DeployProfileName {
    param([string] $ProfileArg)
    switch ($ProfileArg) {
        'commercial' { return 'commercial' }
        'patet-am' { return 'patet-am' }
        default { return 'patet-am' }
    }
}

function Resolve-DeployProfilePath {
    param([string] $ProfileName)
    $profileFile = Join-Path $DeploymentDir "profiles\$ProfileName.env"
    if (Test-Path -LiteralPath $profileFile) {
        return $profileFile
    }
    $legacyName = if ($ProfileName -eq 'commercial') { 'deploy.local.commercial.env' } else { 'deploy.local.env' }
    $legacyFile = Join-Path $DeploymentDir $legacyName
    if (Test-Path -LiteralPath $legacyFile) {
        return $legacyFile
    }
    $exampleFile = Join-Path $DeploymentDir "profiles\$ProfileName.env.example"
    throw "Missing deploy profile. Copy $exampleFile to profiles\$ProfileName.env (or legacy $legacyName) and set PATET_SSH_HOST / PATET_SSH_USER."
}

function Import-DeployProfile {
    param([string] $ProfileName)
    $script:FrontendBuildEnv = @{}
    $script:DeployProfileLabel = ''
    $script:DeployProfileName = $ProfileName
    $path = Resolve-DeployProfilePath -ProfileName $ProfileName
    $loaded = Import-DeployLocalEnv -Path $path
    if (-not $loaded) {
        throw "Failed to load deploy profile: $path"
    }
    if (-not $script:DeployProfileLabel) {
        $script:DeployProfileLabel = $ProfileName
    }
}

function Get-FrontendProductionLocalPath {
    param([string] $RepoPath)
    return Join-Path $RepoPath '.env.production.local'
}

function Apply-FrontendBuildProfile {
    param([string] $RepoPath)
    if ($script:FrontendBuildEnv.Count -eq 0) {
        Write-Warning 'No FRONTEND_BUILD_* vars in deploy profile; frontend build uses local .env only.'
        return
    }
    $outPath = Get-FrontendProductionLocalPath -RepoPath $RepoPath
    $lines = @(
        '# Auto-generated by deploy-from-windows.ps1 — do not commit',
        "# Profile: $script:DeployProfileName ($script:DeployProfileLabel)"
    )
    foreach ($key in ($script:FrontendBuildEnv.Keys | Sort-Object)) {
        $lines += "$key=$($script:FrontendBuildEnv[$key])"
    }
    Set-Content -LiteralPath $outPath -Value $lines -Encoding utf8
    Write-SubStep "Wrote $outPath from deploy profile ($($script:FrontendBuildEnv.Count) vars)"
}

function Remove-FrontendBuildProfile {
    param([string] $RepoPath)
    $outPath = Get-FrontendProductionLocalPath -RepoPath $RepoPath
    if (Test-Path -LiteralPath $outPath) {
        Remove-Item -LiteralPath $outPath -Force -ErrorAction SilentlyContinue
        Write-SubStep "Removed $outPath"
    }
}

function Resolve-RepoPath([string] $RelativeOrAbsolute) {
    if ([System.IO.Path]::IsPathRooted($RelativeOrAbsolute)) {
        return $RelativeOrAbsolute
    }
    return Join-Path $BackAndFrontRoot $RelativeOrAbsolute
}

function Get-ReleaseTimestamp {
    if ($ReleaseId) { return $ReleaseId }
    $now = [DateTime]::UtcNow
    # Windows uses "Caucasus Standard Time"; IANA "Asia/Yerevan" works on .NET 6+ / PowerShell 7+.
    foreach ($tzId in @('Caucasus Standard Time', 'Asia/Yerevan')) {
        try {
            $tz = [TimeZoneInfo]::FindSystemTimeZoneById($tzId)
            $now = [TimeZoneInfo]::ConvertTimeFromUtc($now, $tz)
            break
        }
        catch { }
    }
    if ($now.Kind -eq [DateTimeKind]::Utc) {
        Write-Warning 'Could not resolve Asia/Yerevan timezone; release id will use UTC.'
    }
    return $now.ToString('yyyy-MM-dd_HHmmss')
}

function Assert-Command([string] $Name) {
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command not found: $Name"
    }
}

function Write-UploadShaFile {
    param(
        [string] $RepoPath
    )
    Assert-Command git
    Push-Location $RepoPath
    try {
        $sha = (git rev-parse HEAD).Trim()
        if ($sha -notmatch '^[a-f0-9]{7,40}$') {
            throw "git rev-parse HEAD returned unexpected value in $RepoPath"
        }
        Set-Content -LiteralPath (Join-Path $RepoPath '.patet-upload-sha') -Value $sha -NoNewline
        Write-Host "Wrote .patet-upload-sha ($sha)"
    }
    finally {
        Pop-Location
    }
}

function Invoke-YarnBuild {
    param(
        [string] $RepoPath,
        [ValidateSet('backend', 'frontend')]
        [string] $Kind
    )
    Write-Step "Building $Kind in $RepoPath"
    $frontendProfileApplied = $false
    Push-Location $RepoPath
    try {
        Assert-Command yarn
        # DevDependencies (typescript, @nestjs/cli, etc.) are required for yarn build.
        Remove-Item Env:NODE_ENV -ErrorAction SilentlyContinue
        if ($Kind -eq 'frontend') {
            Apply-FrontendBuildProfile -RepoPath $RepoPath
            $frontendProfileApplied = $true
            foreach ($lock in @('package-lock.json', 'npm-shrinkwrap.json')) {
                $p = Join-Path $RepoPath $lock
                if (Test-Path $p) { Remove-Item $p -Force }
            }
            # .next/trace is often locked after `next dev` and breaks build + tar on Windows.
            foreach ($stale in @('.next\trace', '.next\cache')) {
                $p = Join-Path $RepoPath $stale
                try {
                    if (-not (Test-Path -LiteralPath $p -ErrorAction Stop)) { continue }
                    Write-SubStep "Removing stale $stale before build..."
                    Remove-Item -LiteralPath $p -Recurse -Force -ErrorAction Stop
                }
                catch {
                    throw @"
Cannot access $stale (file may be locked by a running 'next dev' or Node process).
Stop the dev server, delete .next\trace manually, then retry deploy.
"@
                }
            }
        }
        yarn install
        if ($Kind -eq 'frontend') {
            $env:NODE_ENV = 'production'
            $nextDir = Join-Path $RepoPath '.next'
            if (Test-Path $nextDir) {
                Remove-Item -Recurse -Force $nextDir
            }
        }
        yarn build
        if ($Kind -eq 'frontend') {
            Remove-Item Env:NODE_ENV -ErrorAction SilentlyContinue
        }
        if ($Kind -eq 'backend') {
            $mainJs = Join-Path $RepoPath 'dist\src\main.js'
            if (-not (Test-Path $mainJs)) {
                throw "Backend build missing dist\src\main.js"
            }
        }
        else {
            $buildId = Join-Path $RepoPath '.next\BUILD_ID'
            if (-not (Test-Path $buildId)) {
                throw "Frontend build missing .next\BUILD_ID"
            }
        }
        Write-UploadShaFile -RepoPath $RepoPath
    }
    finally {
        if ($frontendProfileApplied) {
            Remove-FrontendBuildProfile -RepoPath $RepoPath
        }
        Pop-Location
    }
}

function Write-SubStep([string] $Message) {
    Write-Host ("  [{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $Message)
}

# Shared upload excludes. .next/cache is dev-only (~hundreds of MB); .next/trace is often locked on Windows.
function Get-PatetUploadExcludeNames {
    return @(
        'node_modules',
        '.git',
        '.next/cache',
        '.next/trace',
        '.env',
        '.env.*',
        'coverage',
        '.cursor',
        '.turbo',
        '.vscode'
    )
}

function Get-SshOptionArgs {
    $extra = $env:PATET_SSH_EXTRA_ARGS
    if (-not $extra) { return @() }
    return @($extra -split '\s+')
}

# OpenSSH on Windows can block in PowerShell until Enter is pressed (stdin still attached).
# -n redirects stdin from /dev/null for non-interactive deploy steps.
function Get-DeployTransportSshArgs {
    $opts = @(Get-SshOptionArgs)
    if ($opts -notcontains '-n') {
        return @('-n') + $opts
    }
    return $opts
}

function Invoke-ExternalWithClosedStdin {
    param(
        [Parameter(Mandatory)]
        [string] $FilePath,
        [Parameter(Mandatory)]
        [string[]] $ArgumentList
    )
    $nullInput = [IO.Path]::GetTempFileName()
    try {
        $p = Start-Process -FilePath $FilePath -ArgumentList $ArgumentList -Wait -PassThru -NoNewWindow `
            -RedirectStandardInput $nullInput
        if ($p.ExitCode -ne 0) {
            throw "$FilePath failed with exit code $($p.ExitCode)"
        }
    }
    finally {
        Remove-Item -LiteralPath $nullInput -Force -ErrorAction SilentlyContinue
    }
}

function Get-SshIdentityPath {
    $opts = Get-SshOptionArgs
    for ($i = 0; $i -lt ($opts.Count - 1); $i++) {
        if ($opts[$i] -eq '-i') {
            return $opts[$i + 1]
        }
    }
    return $null
}

function Test-UsesPuttyIdentity {
    $identity = Get-SshIdentityPath
    return ($identity -and $identity -match '\.ppk$' -and (Test-Path -LiteralPath $identity))
}

function Get-PuttyCommonArgs {
    $puttyArgs = @('-batch')
    $identity = Get-SshIdentityPath
    if ($identity) {
        $puttyArgs += '-i', $identity
    }
    if ($env:PATET_SSH_HOSTKEY) {
        $puttyArgs += '-hostkey', $env:PATET_SSH_HOSTKEY
    }
    return $puttyArgs
}

function Invoke-DeploySsh {
    param(
        [string] $SshTarget,
        [string] $RemoteCommand
    )
    if (Test-UsesPuttyIdentity) {
        Assert-Command plink
        $plinkArgs = @(Get-PuttyCommonArgs) + @($SshTarget, $RemoteCommand)
        Write-Host "plink $($plinkArgs -join ' ')"
        & plink @plinkArgs
        if ($LASTEXITCODE -ne 0) { throw "plink failed with exit code $LASTEXITCODE" }
        return
    }
    $sshArgs = @(Get-DeployTransportSshArgs) + @($SshTarget, $RemoteCommand)
    Write-Host "ssh $($sshArgs -join ' ')"
    & ssh @sshArgs
    if ($LASTEXITCODE -ne 0) { throw "ssh failed with exit code $LASTEXITCODE" }
}

function Invoke-DeployScp {
    param(
        [string] $LocalPath,
        [string] $RemoteSpec
    )
    if (Test-UsesPuttyIdentity) {
        Assert-Command pscp
        $pscpArgs = @(Get-PuttyCommonArgs) + @($LocalPath, $RemoteSpec)
        Write-Host "pscp $($pscpArgs -join ' ')"
        & pscp @pscpArgs
        if ($LASTEXITCODE -ne 0) { throw "pscp failed with exit code $LASTEXITCODE" }
        return
    }
    $scpArgs = @(Get-SshOptionArgs) + @($LocalPath, $RemoteSpec)
    Write-Host "scp $($scpArgs -join ' ')"
    Invoke-ExternalWithClosedStdin -FilePath 'scp' -ArgumentList $scpArgs
}

function Assert-DeployTransportCommands {
    if (Test-UsesPuttyIdentity) {
        Assert-Command plink
        Assert-Command pscp
        return
    }
    Assert-Command ssh
    Assert-Command scp
}

function Get-RsyncRshArg {
    if (Test-UsesPuttyIdentity) { return @() }
    $sshOpts = Get-DeployTransportSshArgs
    if ($sshOpts.Count -eq 0) { return @('-e', 'ssh -n') }
    return @('-e', ('ssh ' + ($sshOpts -join ' ')))
}

function Invoke-WslQuiet {
    param([string[]] $WslArgs)
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'SilentlyContinue'
    try {
        & wsl @WslArgs 2>$null | Out-Null
        return $LASTEXITCODE
    }
    finally {
        $ErrorActionPreference = $prevEap
    }
}

function Get-RsyncMode {
    if (Test-UsesPuttyIdentity) { return $null }
    if (Get-Command rsync -ErrorAction SilentlyContinue) { return 'native' }
    if (Get-Command wsl -ErrorAction SilentlyContinue) {
        if ((Invoke-WslQuiet -WslArgs @('-e', 'sh', '-c', 'command -v rsync >/dev/null 2>&1')) -eq 0) {
            return 'wsl'
        }
    }
    return $null
}

function Convert-WindowsPathForWsl {
    param([string] $WindowsPath)
    $normalized = $WindowsPath.TrimEnd('\', '/')
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'SilentlyContinue'
    try {
        $out = (wsl wslpath -a "$normalized" 2>$null).Trim()
        if ($LASTEXITCODE -ne 0 -or -not $out -or $out -notmatch '^/') {
            return $null
        }
        return $out
    }
    finally {
        $ErrorActionPreference = $prevEap
    }
}

function Invoke-RsyncRelease {
    param(
        [string] $LocalPath,
        [string] $RemotePath,
        [string] $SshTarget
    )
    $excludes = @()
    foreach ($name in Get-PatetUploadExcludeNames) {
        $excludes += '--exclude', "$name/"
        $excludes += '--exclude', $name
    }
    $excludes += '--exclude', '*.log'
    $mode = Get-RsyncMode
    if (-not $mode) {
        return $false
    }

    $localTrail = $LocalPath.TrimEnd('\') + [IO.Path]::DirectorySeparatorChar
    $remote = "${SshTarget}:${RemotePath}/"
    $rsh = Get-RsyncRshArg

    try {
        if ($mode -eq 'wsl') {
            $wslLocal = Convert-WindowsPathForWsl -WindowsPath $localTrail
            if (-not $wslLocal) {
                Write-Warning 'wslpath failed; falling back to tar+scp.'
                return $false
            }
            $args = @(
                'rsync', '-avz', '--delete'
            ) + $rsh + $excludes + @($wslLocal, $remote)
            Write-Host "wsl $($args -join ' ')"
            & wsl @args
        }
        else {
            $args = @('-avz', '--delete') + $rsh + $excludes + @($localTrail, $remote)
            Write-Host "rsync $($args -join ' ')"
            & rsync @args
        }
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "rsync failed (exit $LASTEXITCODE); falling back to tar+scp."
            return $false
        }
        return $true
    }
    catch {
        Write-Warning "rsync error: $_; falling back to tar+scp."
        return $false
    }
}

function Invoke-ScpTarRelease {
    param(
        [string] $LocalPath,
        [string] $RemotePath,
        [string] $SshTarget
    )
    Write-Step "Uploading via tar+scp (rsync not available)"
    Assert-Command tar
    Assert-DeployTransportCommands

    $archive = Join-Path $env:TEMP ("patet-release-{0}.tgz" -f [Guid]::NewGuid().ToString('N'))
    try {
        $tarArgs = @('-czf', $archive)
        foreach ($name in Get-PatetUploadExcludeNames) {
            $tarArgs += "--exclude=$name"
        }
        $tarArgs += '-C', $LocalPath, '.'

        Write-SubStep 'Creating compressed archive (excludes node_modules, .git, .next/cache, .next/trace)...'
        $sw = [Diagnostics.Stopwatch]::StartNew()
        & tar @tarArgs 2>&1 | ForEach-Object { Write-SubStep $_ }
        if ($LASTEXITCODE -ne 0) {
            throw "tar create failed (exit $LASTEXITCODE). Close apps locking .next (e.g. next dev) and retry."
        }
        $sizeMb = [math]::Round((Get-Item -LiteralPath $archive).Length / 1MB, 1)
        Write-SubStep ("Archive ready: {0} MB in {1:mm\:ss}" -f $sizeMb, $sw.Elapsed)

        $remoteParent = ($RemotePath -replace '/[^/]+$','')
        Write-SubStep 'Ensuring remote release directory exists...'
        Invoke-DeploySsh -SshTarget $SshTarget -RemoteCommand "mkdir -p '$remoteParent' '$RemotePath'"

        Write-SubStep ("Uploading {0} MB to server (scp)..." -f $sizeMb)
        $sw.Restart()
        Invoke-DeployScp -LocalPath $archive -RemoteSpec "${SshTarget}:/tmp/patet-release.tgz"
        Write-SubStep ("Upload finished in {0:mm\:ss}" -f $sw.Elapsed)

        Write-SubStep 'Extracting on server...'
        $sw.Restart()
        Invoke-DeploySsh -SshTarget $SshTarget -RemoteCommand "rm -rf '$RemotePath' && mkdir -p '$RemotePath' && tar -xzf /tmp/patet-release.tgz -C '$RemotePath' && rm -f /tmp/patet-release.tgz"
        Write-SubStep ("Extract finished in {0:mm\:ss}" -f $sw.Elapsed)
    }
    finally {
        if (Test-Path -LiteralPath $archive) {
            Remove-Item -LiteralPath $archive -Force -ErrorAction SilentlyContinue
        }
    }
}

function Invoke-UploadRelease {
    param(
        [string] $LocalPath,
        [string] $RemotePath,
        [string] $SshTarget
    )
    Write-Step "Upload $LocalPath -> $RemotePath"
    $usedRsync = Invoke-RsyncRelease -LocalPath $LocalPath -RemotePath $RemotePath -SshTarget $SshTarget
    if (-not $usedRsync) {
        Invoke-ScpTarRelease -LocalPath $LocalPath -RemotePath $RemotePath -SshTarget $SshTarget
    }
}

function Invoke-Ssh {
    param([string] $RemoteCommand)
    $sshTarget = "${env:PATET_SSH_USER}@${env:PATET_SSH_HOST}"
    Invoke-DeploySsh -SshTarget $sshTarget -RemoteCommand $RemoteCommand
}

function Read-NumberChoice {
    param(
        [string] $Title,
        [string[]] $Options,
        [int] $DefaultIndex = 1
    )
    Write-Host ''
    Write-Host $Title
    for ($i = 0; $i -lt $Options.Count; $i++) {
        $n = $i + 1
        $mark = if ($n -eq $DefaultIndex) { ' (default)' } else { '' }
        Write-Host ("  [{0}] {1}{2}" -f $n, $Options[$i], $mark)
    }
    $max = $Options.Count
    while ($true) {
        $raw = Read-Host ("Enter choice (1-{0}, Enter={1})" -f $max, $DefaultIndex)
        if ([string]::IsNullOrWhiteSpace($raw)) {
            return $DefaultIndex
        }
        if ($raw -match '^\d+$') {
            $pick = [int]$raw
            if ($pick -ge 1 -and $pick -le $max) {
                return $pick
            }
        }
        Write-Host "Invalid choice. Enter a number from 1 to $max." -ForegroundColor Yellow
    }
}

function Get-DeployManualCommandLines {
    $cmd = [System.Collections.Generic.List[string]]::new()
    $wrapper = if ($script:DeployProfileName -eq 'commercial') { '.\deploy-commercial.ps1' } else { '.\deploy-patet.ps1' }
    $cmd.Add($wrapper)
    if ($Target -ne 'all') {
        $cmd.Add('-Target')
        $cmd.Add($Target)
    }
    if ($Migrate) { $cmd.Add('-Migrate') }
    if ($SyncDeploymentScripts) { $cmd.Add('-SyncDeploymentScripts') }
    if ($SkipBuild) { $cmd.Add('-SkipBuild') }
    if ($SkipUpload) { $cmd.Add('-SkipUpload') }
    if ($ReleaseId) {
        $cmd.Add('-ReleaseId')
        $cmd.Add(('"{0}"' -f $ReleaseId))
    }

    return @(
        "cd `"$DeploymentDir`""
        ($cmd -join ' ')
    )
}

function Write-DeployManualCommand {
    Write-Host ''
    Write-Host 'Copy for next time (non-interactive):' -ForegroundColor DarkCyan
    foreach ($line in (Get-DeployManualCommandLines)) {
        Write-Host "  $line"
    }
}

function Write-DeploySummary {
    param([string] $SummaryLine)

    Write-Host ''
    Write-Host 'Starting deploy:' -ForegroundColor Cyan
    Write-Host "  $SummaryLine"
    Write-DeployManualCommand
}

function Invoke-DeployInteractiveQuick {
    param(
        [ValidateSet('backend', 'frontend', 'all')]
        [string] $DeployTarget = 'all',

        [bool] $WithMigrate = $false
    )

    $script:Target = $DeployTarget
    $script:Migrate = $WithMigrate
    $script:SyncDeploymentScripts = $false
    $script:SkipBuild = $false
    $script:SkipUpload = $false

    $targetLabel = switch ($DeployTarget) {
        'backend' { 'backend only' }
        'frontend' { 'frontend only' }
        default { 'backend + frontend' }
    }
    $migrateLabel = if ($DeployTarget -eq 'frontend') {
        'n/a'
    }
    elseif ($WithMigrate) {
        'yes'
    }
    else {
        'no'
    }
    Write-DeploySummary -SummaryLine "Quick: $targetLabel, full build + upload + finalize, migrations=$migrateLabel, no script sync"
}

function Invoke-DeployInteractiveDetailed {
    $targetPick = Read-NumberChoice -Title 'What to deploy?' -Options @(
        'Backend only (patet-api)',
        'Frontend only (patet-website)',
        'Both (backend + frontend)'
    ) -DefaultIndex 3
    switch ($targetPick) {
        1 { $script:Target = 'backend' }
        2 { $script:Target = 'frontend' }
        default { $script:Target = 'all' }
    }

    $includesBackend = $script:Target -eq 'backend' -or $script:Target -eq 'all'
    if ($includesBackend) {
        $migratePick = Read-NumberChoice -Title 'Run backend migrations during finalize?' -Options @(
            'No - skip migrations',
            'Yes - run yarn migration:run on server'
        ) -DefaultIndex 1
        $script:Migrate = ($migratePick -eq 2)
    }
    else {
        $script:Migrate = $false
    }

    $syncPick = Read-NumberChoice -Title 'Sync deployment scripts to server before finalize?' -Options @(
        'No',
        'Yes (finalize-release.sh, deploy-common.sh, etc.)'
    ) -DefaultIndex 1
    $script:SyncDeploymentScripts = ($syncPick -eq 2)

    $modePick = Read-NumberChoice -Title 'Deploy mode?' -Options @(
        'Full - build locally, upload, finalize on server',
        'Build only - no upload or finalize',
        'Upload + finalize only - skip local build (artifacts must exist)'
    ) -DefaultIndex 1
    switch ($modePick) {
        2 {
            $script:SkipBuild = $false
            $script:SkipUpload = $true
        }
        3 {
            $script:SkipBuild = $true
            $script:SkipUpload = $false
        }
        default {
            $script:SkipBuild = $false
            $script:SkipUpload = $false
        }
    }

    if ($script:SkipBuild -and -not $script:ReleaseId) {
        $reuse = Read-NumberChoice -Title 'Reuse an existing release folder on the server?' -Options @(
            'No - generate a new release id (timestamp)',
            'Yes - enter an existing release id'
        ) -DefaultIndex 1
        if ($reuse -eq 2) {
            $script:ReleaseId = (Read-Host 'Release id (e.g. 2026-05-22_161454)').Trim()
            if ([string]::IsNullOrWhiteSpace($script:ReleaseId)) {
                throw 'Release id is required when skipping build without a new timestamp.'
            }
        }
    }

    $migrateSummary = if ($includesBackend) { if ($Migrate) { 'yes' } else { 'no' } } else { 'n/a' }
    $modeSummary = if ($SkipUpload) { 'build only' } elseif ($SkipBuild) { 'upload + finalize' } else { 'full' }
    $summary = "Target=$Target, migrations=$migrateSummary, sync scripts=$(if ($SyncDeploymentScripts) { 'yes' } else { 'no' }), mode=$modeSummary"
    if ($ReleaseId) { $summary += ", release id=$ReleaseId" }
    Write-DeploySummary -SummaryLine $summary
}

function Invoke-DeployInteractivePrompts {
    Write-Host ''
    $profileHint = if ($script:DeployProfileLabel) { " - $script:DeployProfileLabel" } else { '' }
    Write-Host "Patet Windows deploy$profileHint" -ForegroundColor Cyan

    $entryPick = Read-NumberChoice -Title 'What do you want to do?' -Options @(
        'Backend only',
        'Frontend only',
        'Backend + frontend',
        'Backend + frontend + migrations',
        'More options (sync scripts, deploy mode, release id, etc.)'
    ) -DefaultIndex 3

    switch ($entryPick) {
        1 { Invoke-DeployInteractiveQuick -DeployTarget backend -WithMigrate:$false }
        2 { Invoke-DeployInteractiveQuick -DeployTarget frontend -WithMigrate:$false }
        3 { Invoke-DeployInteractiveQuick -DeployTarget all -WithMigrate:$false }
        4 { Invoke-DeployInteractiveQuick -DeployTarget all -WithMigrate:$true }
        default { Invoke-DeployInteractiveDetailed }
    }
}

function Sync-DeploymentScriptsToServer {
    param([string] $SshTarget)
    $dest = $env:PATET_DEPLOYMENT_ROOT
    if (-not $dest) { $dest = '/var/www/patet-deployment' }
    $files = @(
        'deploy-config.sh',
        'deploy-common.sh',
        'finalize-release.sh',
        'ecosystem.config.js'
    )
    foreach ($f in $files) {
        $local = Join-Path $DeploymentDir $f
        if (-not (Test-Path $local)) { continue }
        Write-Host "Uploading deployment script $f"
        Invoke-DeployScp -LocalPath $local -RemoteSpec "${SshTarget}:${dest}/$f"
    }
    Invoke-Ssh "sed -i 's/\r$//' '$dest'/*.sh 2>/dev/null || true; chmod +x '$dest/finalize-release.sh' '$dest/deploy.sh' '$dest/rollback.sh' 2>/dev/null || true"
}

# --- main ---

$resolvedProfile = Resolve-DeployProfileName -ProfileArg $Profile
Import-DeployProfile -ProfileName $resolvedProfile

if (-not $env:PATET_SSH_HOST -or -not $env:PATET_SSH_USER) {
    throw "PATET_SSH_HOST and PATET_SSH_USER must be set in deploy profile (profiles\$resolvedProfile.env)"
}

$explicitDeployOpts = @('Target', 'SkipBuild', 'Migrate', 'SkipUpload', 'SyncDeploymentScripts', 'ReleaseId')
$hasExplicitDeployOpts = $false
foreach ($optName in $explicitDeployOpts) {
    if ($PSBoundParameters.ContainsKey($optName)) {
        $hasExplicitDeployOpts = $true
        break
    }
}
if (-not $hasExplicitDeployOpts) {
    Invoke-DeployInteractivePrompts
}

$apiRoot = if ($env:PATET_API_ROOT) { $env:PATET_API_ROOT } else { '/var/www/patet-api' }
$webRoot = if ($env:PATET_WEB_ROOT) { $env:PATET_WEB_ROOT } else { '/var/www/patet-website' }
$deployRoot = if ($env:PATET_DEPLOYMENT_ROOT) { $env:PATET_DEPLOYMENT_ROOT } else { '/var/www/patet-deployment' }

$backendLocal = Resolve-RepoPath ($(if ($env:PATET_LOCAL_BACKEND) { $env:PATET_LOCAL_BACKEND } else { 'patet-back-nestjs' }))
$frontendLocal = Resolve-RepoPath ($(if ($env:PATET_LOCAL_FRONTEND) { $env:PATET_LOCAL_FRONTEND } else { 'patet-website' }))

$release = Get-ReleaseTimestamp
$sshTarget = "$($env:PATET_SSH_USER)@$($env:PATET_SSH_HOST)"

Write-Host ''
Write-Host "Deploy profile: $script:DeployProfileLabel" -ForegroundColor Green
Write-Host "SSH target:     $sshTarget" -ForegroundColor Green
if ($script:FrontendBuildEnv.Count -gt 0) {
    Write-Host "Frontend build: $($script:FrontendBuildEnv.Count) vars from profile (FRONTEND_BUILD_*)" -ForegroundColor Green
}

Write-Step "Patet Windows deploy - profile=$resolvedProfile target=$Target release=$release"
if ($hasExplicitDeployOpts) {
    Write-DeployManualCommand
}

$doBackend = $Target -eq 'backend' -or $Target -eq 'all'
$doFrontend = $Target -eq 'frontend' -or $Target -eq 'all'

if (-not $SkipBuild) {
    if ($doBackend) { Invoke-YarnBuild -RepoPath $backendLocal -Kind backend }
    if ($doFrontend) { Invoke-YarnBuild -RepoPath $frontendLocal -Kind frontend }
}

if ($SkipUpload) {
    Write-Host "SkipUpload set - done after build."
    exit 0
}

Assert-DeployTransportCommands

if ($SyncDeploymentScripts) {
    Sync-DeploymentScriptsToServer -SshTarget $sshTarget
}

if ($doBackend) {
    $remoteBackend = "$apiRoot/releases/$release"
    Invoke-UploadRelease -LocalPath $backendLocal -RemotePath $remoteBackend -SshTarget $sshTarget
}

if ($doFrontend) {
    $remoteFrontend = "$webRoot/releases/$release"
    Invoke-UploadRelease -LocalPath $frontendLocal -RemotePath $remoteFrontend -SshTarget $sshTarget
}

$finalizeArgs = @($Target, $release)
if ($Migrate) { $finalizeArgs += '--with-migrate' }

$finalizeCmd = "cd '$deployRoot' && bash ./finalize-release.sh $($finalizeArgs -join ' ')"
Write-Step "Finalizing on server"
Invoke-Ssh -RemoteCommand $finalizeCmd

Write-Step "Deploy finished"
Write-Host "Release id: $release"
Write-Host "Check status on server: ssh $sshTarget `"cd $deployRoot && ./deploy.sh status all`""
