#!/usr/bin/env bash
# Server 2: nginx wildcard vhost + TLS for commercial SaaS (parcel-ops.com).
# Recommended: Let's Encrypt wildcard via Cloudflare DNS + Cloudflare SSL Full (strict).
#
# Usage (on commercial VPS as root):
#   export PLATFORM_DOMAIN=parcel-ops.com
#   export CERTBOT_EMAIL=you@company.com
#   export CLOUDFLARE_DNS_API_TOKEN=your_cf_api_token   # Zone DNS Edit for parcel-ops.com
#   bash /var/www/patet-deployment/scripts/provision-commercial-nginx.sh
#
# Alternative (no API token): place Cloudflare Origin Certificate files and re-run:
#   /etc/ssl/cloudflare/parcel-ops.com.crt
#   /etc/ssl/cloudflare/parcel-ops.com.key

set -euo pipefail

PLATFORM_DOMAIN="${PLATFORM_DOMAIN:-parcel-ops.com}"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-admin@${PLATFORM_DOMAIN}}"
NGINX_SITE="/etc/nginx/sites-available/${PLATFORM_DOMAIN}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${PLATFORM_DOMAIN}"
LE_LIVE="/etc/letsencrypt/live/${PLATFORM_DOMAIN}"
CF_ORIGIN_CRT="/etc/ssl/cloudflare/${PLATFORM_DOMAIN}.crt"
CF_ORIGIN_KEY="/etc/ssl/cloudflare/${PLATFORM_DOMAIN}.key"
CF_SECRETS="/root/.secrets/cloudflare.ini"

log() { echo "==== $* ===="; }

require_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "Run as root"
    exit 1
  fi
}

install_packages() {
  log "Installing nginx + certbot DNS plugin"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y nginx certbot python3-certbot-dns-cloudflare
}

write_nginx_config() {
  local cert_fullchain="$1"
  local cert_key="$2"

  log "Writing nginx site ${NGINX_SITE}"
  cat >"$NGINX_SITE" <<EOF
# Patet commercial — ${PLATFORM_DOMAIN} (generated by provision-commercial-nginx.sh)

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${PLATFORM_DOMAIN} *.${PLATFORM_DOMAIN};

    ssl_certificate     ${cert_fullchain};
    ssl_certificate_key ${cert_key};
    ssl_session_timeout 1d;
    ssl_session_cache shared:PatetCommercialSSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://127.0.0.1:4993;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:57303;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /fulfillment-product-images/ {
        proxy_pass http://127.0.0.1:57303;
        proxy_set_header Host \$host;
    }

    location /marketplace-product-images/ {
        proxy_pass http://127.0.0.1:57303;
        proxy_set_header Host \$host;
    }

    location /marketplace-shop-images/ {
        proxy_pass http://127.0.0.1:57303;
        proxy_set_header Host \$host;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name ${PLATFORM_DOMAIN} *.${PLATFORM_DOMAIN};
    return 301 https://\$host\$request_uri;
}
EOF
}

obtain_letsencrypt_cert() {
  if [[ -f "${LE_LIVE}/fullchain.pem" && -f "${LE_LIVE}/privkey.pem" ]]; then
    log "Let's Encrypt cert already present at ${LE_LIVE}"
    return 0
  fi

  if [[ -f "$CF_ORIGIN_CRT" && -f "$CF_ORIGIN_KEY" ]]; then
    log "Using Cloudflare Origin Certificate at ${CF_ORIGIN_CRT}"
    return 0
  fi

  if [[ -z "${CLOUDFLARE_DNS_API_TOKEN:-}" ]]; then
    if [[ -f "$CF_SECRETS" ]]; then
      # shellcheck disable=SC1090
      CLOUDFLARE_DNS_API_TOKEN="$(grep -E '^dns_cloudflare_api_token\s*=' "$CF_SECRETS" | head -1 | cut -d= -f2- | tr -d ' \"')"
    fi
  fi

  if [[ -z "${CLOUDFLARE_DNS_API_TOKEN:-}" ]]; then
    echo "Missing CLOUDFLARE_DNS_API_TOKEN (or ${CF_SECRETS})."
    echo "Create a Cloudflare API token: Zone → DNS → Edit for ${PLATFORM_DOMAIN}."
    echo "Or place Origin Certificate at ${CF_ORIGIN_CRT} and ${CF_ORIGIN_KEY}."
    return 1
  fi

  log "Obtaining Let's Encrypt wildcard cert (DNS-01 via Cloudflare)"
  install -d -m 0700 /root/.secrets
  cat >"$CF_SECRETS" <<EOF
dns_cloudflare_api_token = ${CLOUDFLARE_DNS_API_TOKEN}
EOF
  chmod 0600 "$CF_SECRETS"

  certbot certonly \
    --dns-cloudflare \
    --dns-cloudflare-credentials "$CF_SECRETS" \
    --dns-cloudflare-propagation-seconds 30 \
    -d "${PLATFORM_DOMAIN}" \
    -d "*.${PLATFORM_DOMAIN}" \
    --agree-tos \
    --non-interactive \
    --email "$CERTBOT_EMAIL" \
    --keep-until-expiring
}

resolve_cert_paths() {
  if [[ -f "${LE_LIVE}/fullchain.pem" && -f "${LE_LIVE}/privkey.pem" ]]; then
    CERT_FULLCHAIN="${LE_LIVE}/fullchain.pem"
    CERT_KEY="${LE_LIVE}/privkey.pem"
    return 0
  fi
  if [[ -f "$CF_ORIGIN_CRT" && -f "$CF_ORIGIN_KEY" ]]; then
    CERT_FULLCHAIN="$CF_ORIGIN_CRT"
    CERT_KEY="$CF_ORIGIN_KEY"
    return 0
  fi
  return 1
}

enable_nginx_site() {
  log "Enabling nginx site and disabling default"
  ln -sfn "$NGINX_SITE" "$NGINX_ENABLED"
  rm -f /etc/nginx/sites-enabled/default
  nginx -t
  systemctl enable nginx
  systemctl reload nginx
}

main() {
  require_root
  install_packages

  if ! obtain_letsencrypt_cert; then
    exit 1
  fi

  if ! resolve_cert_paths; then
    echo "No TLS certificate files found after obtain step."
    exit 1
  fi

  write_nginx_config "$CERT_FULLCHAIN" "$CERT_KEY"
  enable_nginx_site

  log "Done"
  echo "Verify on server:"
  echo "  curl -fsSI -H 'Host: ${PLATFORM_DOMAIN}' https://127.0.0.1/ --insecure | head -3"
  echo "Cloudflare dashboard → SSL/TLS → Overview → set mode to Full (strict)."
  echo "DNS: ${PLATFORM_DOMAIN} and * → 67.205.168.134 (proxied orange cloud OK)."
}

main "$@"
